package at.aau.serg.websocketdemoserver.messaging.dtos;

public enum ErrorCode {
    INVALID_COMMAND,
    MISSING_COMMAND_TYPE,
    MISSING_PLAYER_ID,
    LOBBY_NOT_FOUND,
    GAME_ALREADY_STARTED,
    CANNOT_JOIN_STARTED_GAME,
    PLAYER_ALREADY_JOINED,
    PLAYER_NOT_IN_LOBBY,
    MIN_PLAYERS_NOT_REACHED,
    INVALID_PHASE,
    CURRENT_PLAYER_NOT_SET,
    NOT_YOUR_TURN,
    DICE_ALREADY_ROLLED,
    ROLL_REQUIRED_BEFORE_MOVE,
    MISSING_MOVE_STEPS,
    INVALID_MOVE_STEPS,
    UNSUPPORTED_COMMAND_TYPE,
    INTERNAL_ERROR,
    LOBBY_FULL,
    CITY_NOT_FOUND,
    INVALID_MOVE_TARGET
}
